image: maven:3.9.5-openjdk-17

stages:
- build
- test

cache:
  paths:
  - .m2/repository/
  - target/

build:
  stage: build
  script:
  - mvn clean package -DskipTests=true

test:
  stage: test
  script:
  - mvn test -Pweb-execution -Dsuite=local -Dtarget=local -Dheadless=true -Dbrowser=chrome
