pipeline {
    agent any

    environment {
        MVN_HOME = tool 'M3'
    }

    stages {
        stage('Preparation') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'token', variable: 'GIT_TOKEN')]) {
                        git url: "https://github.com/ulucasfraga/selenium-e2e/tests.git", credentialsId: 'token'
                    }
                }
            }
        }

        stage('Build') {
            steps {
                bat "\"%MVN_HOME%\\bin\\mvn\" clean package -DskipTests=true"
            }
        }

        stage('Test Execution') {
            steps {
                script {
                    try {
                        bat "\"%MVN_HOME%\\bin\\mvn\" test -Pweb-execution -Dsuite=local -Dtarget=local -Dheadless=true -Dbrowser=chrome"
                    } catch (Exception e) {
                        currentBuild.result = 'FAILURE'
                    } finally {
                        junit '**/target/surefire-reports/TEST-*.xml'

                        publishHTML(target: [
                            allowMissing: false,
                            alwaysLinkToLastBuild: true,
                            keepAll: true,
                            reportDir: 'target/surefire-reports',
                            reportFiles: 'index.html',
                            reportName: 'TestNG Report'
                        ])
                    }
                }
            }
        }
    }
}
